//! Rust backend code generation for tpt-telos (Phase 2 milestone).
//!
//! [`generate_program`] lowers a set of parsed modules into a single,
//! self-contained Rust library source string. The generated code:
//!   * declares a `struct` for every user type that is accessed by field,
//!   * attaches an `invariants()` method to each such struct for every
//!     `invariant` block of the same name,
//!   * emits one `fn` per `func`, threading `&mut` only to parameters that are
//!     actually mutated,
//!   * carries the original `requires` / `ensures` contracts as doc-comments.
//!
//! The function bodies come from the agentic transpiler's final candidates
//! (see [`telos_agent`]), so the emitted code is mathematically verified before
//! it is written out.

use std::collections::{BTreeSet, HashMap, HashSet};

use telos_agent::FuncOutcome;
use telos_parser::ast::*;

/// Maps a type name to the set of fields that must appear on its generated
/// struct.
type TypeFields = HashMap<String, BTreeSet<String>>;

/// Generate a full Rust library source for all modules.
///
/// `bodies` supplies the final (verified) body for each function, keyed by
/// `"<module>.<func>"`. A function absent from the map falls back to its body
/// in the parsed source.
pub fn generate_program(modules: &[Module], outcomes: &[FuncOutcome]) -> String {
    let mut bodies: HashMap<String, Vec<Stmt>> = HashMap::new();
    for o in outcomes {
        bodies.insert(o.func_name.clone(), o.final_candidate.stmts.clone());
    }

    let mut out = String::new();
    out.push_str("// Generated by tpt-telos. Do not edit by hand.\n");
    out.push_str("// Mathematical contracts were verified by the tpt-telos SMT core.\n");
    out.push_str("#![allow(dead_code)]\n\n");

    let mut struct_types: TypeFields = HashMap::new();
    for m in modules {
        collect_types(m, &mut struct_types);
    }

    for m in modules {
        out.push_str(&generate_module(m, &bodies, &struct_types));
        out.push('\n');
    }

    out
}

fn collect_types(module: &Module, types: &mut TypeFields) {
    // Field accesses keyed by the *base name* they were written with (usually a
    // parameter name). We re-point these onto the parameter's type afterwards.
    let mut raw_fields: HashMap<String, BTreeSet<String>> = HashMap::new();
    let mut field_users: HashSet<String> = HashSet::new();

    let scan_expr = |e: &Expr, users: &mut HashSet<String>, raw: &mut HashMap<String, BTreeSet<String>>| {
        let mut fields: Vec<(String, String)> = Vec::new();
        collect_fields(e, &mut fields);
        for (base, field) in fields {
            users.insert(base.clone());
            raw.entry(base.clone()).or_default().insert(field);
        }
    };

    for item in &module.items {
        if let Item::Func(f) = item {
            for r in &f.requires {
                scan_expr(r, &mut field_users, &mut raw_fields);
            }
            for e in &f.ensures {
                scan_expr(e, &mut field_users, &mut raw_fields);
            }
            for stmt in &f.body {
                let assigns = match stmt {
                    Stmt::MutateState(a) => a,
                    Stmt::Assign(a) => std::slice::from_ref(a),
                };
                for a in assigns {
                    if let Expr::Field { base, field } = &a.target {
                        field_users.insert(base.clone());
                        raw_fields.entry(base.clone()).or_default().insert(field.clone());
                    }
                    scan_expr(&a.value, &mut field_users, &mut raw_fields);
                }
            }
        }
    }

    // Re-point: a base that is a parameter of a named type is really that
    // *type's* field.
    for item in &module.items {
        if let Item::Func(f) = item {
            for p in &f.params {
                if let Some(fields) = raw_fields.remove(&p.name) {
                    types.entry(p.ty.name().to_string()).or_default().extend(fields);
                }
            }
        }
    }
    // Any bases that were never parameters keep their raw (base-named) fields.
    for (base, fields) in raw_fields {
        types.entry(base).or_default().extend(fields);
    }
}

fn collect_fields(expr: &Expr, out: &mut Vec<(String, String)>) {
    match expr {
        Expr::Field { base, field } => out.push((base.clone(), field.clone())),
        Expr::Old(e) => collect_fields(e, out),
        Expr::Unary { expr, .. } => collect_fields(expr, out),
        Expr::Bin { lhs, rhs, .. } => {
            collect_fields(lhs, out);
            collect_fields(rhs, out);
        }
        _ => {}
    }
}

fn generate_module(
    module: &Module,
    bodies: &HashMap<String, Vec<Stmt>>,
    types: &TypeFields,
) -> String {
    let route = telos_router::route(&module.attributes);
    let mut out = String::new();
    out.push_str(&format!(
        "// ===== module {} (target: {}) =====\n",
        module.name,
        route.target.as_str()
    ));

    // Structs.
    for (ty, fields) in types {
        if fields.is_empty() {
            continue;
        }
        out.push_str(&format!("pub struct {} {{\n", ty));
        for f in fields {
            out.push_str(&format!("    pub {}: i64,\n", f));
        }
        out.push_str("}\n\n");
    }

    // Invariants as `impl` methods.
    for item in &module.items {
        if let Item::Invariant(inv) = item {
            let conds = inv
                .constraints
                .iter()
                .map(render_inv)
                .collect::<Vec<_>>()
                .join(" && ");
            out.push_str(&format!(
                "impl {} {{\n    pub fn satisfies_invariants(&self) -> bool {{\n        {}\n    }}\n}}\n\n",
                inv.name, conds
            ));
        }
    }

    // Functions.
    for item in &module.items {
        if let Item::Func(f) = item {
            let key = f.name.clone();
            let stmts = bodies.get(&key).cloned().unwrap_or_else(|| f.body.clone());
            out.push_str(&render_func(f, &stmts, types));
            out.push('\n');
        }
    }

    out
}

fn render_func(f: &Func, stmts: &[Stmt], types: &TypeFields) -> String {
    let mut out = String::new();

    // Doc-comment carrying the contract.
    out.push_str(&format!("/// {}({})\n", f.name, render_params_sig(f)));
    for r in &f.requires {
        out.push_str(&format!("/// requires: {}\n", render_expr_doc(r)));
    }
    for e in &f.ensures {
        out.push_str(&format!("/// ensures:  {}\n", render_expr_doc(e)));
    }

    // Determine mutated struct params and scalar-return outputs.
    let mut mutated: HashSet<String> = HashSet::new();
    let mut scalar_out: Option<String> = None;
    for stmt in stmts {
        let assigns = match stmt {
            Stmt::MutateState(a) => a,
            Stmt::Assign(a) => std::slice::from_ref(a),
        };
        for a in assigns {
            match &a.target {
                Expr::Field { base, .. } => {
                    mutated.insert(base.clone());
                }
                Expr::Var(v) => {
                    if scalar_out.is_none() {
                        scalar_out = Some(v.clone());
                    }
                }
                _ => {}
            }
        }
    }

    // Build parameter list + return type.
    let mut params = Vec::new();
    for p in &f.params {
        if Some(&p.name) == scalar_out.as_ref() {
            continue; // produced as the return value, not an input
        }
        let ty = p.ty.name();
        let is_struct = types.get(ty).map(|s| !s.is_empty()).unwrap_or(false);
        if is_struct {
            let borrow = if mutated.contains(&p.name) {
                "&mut "
            } else {
                "&"
            };
            params.push(format!("{}: {}{}", p.name, borrow, ty));
        } else {
            params.push(format!("{}: i64", p.name));
        }
    }

    let ret = if scalar_out.is_some() {
        " -> i64"
    } else {
        ""
    };

    out.push_str(&format!("pub fn {}({}){} {{\n", f.name, params.join(", "), ret));

    // Body.
    for stmt in stmts {
        match stmt {
            Stmt::MutateState(assigns) => {
                for a in assigns {
                    out.push_str("    ");
                    out.push_str(&render_assign(a));
                    out.push_str(";\n");
                }
            }
            Stmt::Assign(a) => {
                let value = render_expr(&a.value);
                if scalar_out.as_deref() == Some(target_var(&a.target)) {
                    out.push_str(&format!("    let {} = {};\n", target_var(&a.target), value));
                } else {
                    out.push_str("    ");
                    out.push_str(&render_assign(a));
                    out.push_str(";\n");
                }
            }
        }
    }

    if let Some(outvar) = &scalar_out {
        out.push_str(&format!("    {}\n", outvar));
    }

    out.push_str("}\n");
    out
}

fn render_params_sig(f: &Func) -> String {
    f.params
        .iter()
        .map(|p| format!("{}: {}", p.name, p.ty.name()))
        .collect::<Vec<_>>()
        .join(", ")
}

fn target_var(e: &Expr) -> &str {
    match e {
        Expr::Var(v) => v,
        _ => "",
    }
}

fn render_assign(a: &Assign) -> String {
    let lhs = render_expr(&a.target);
    let rhs = render_expr(&a.value);
    let op = match a.op {
        AssignOp::Set => "=",
        AssignOp::Add => "+=",
        AssignOp::Sub => "-=",
    };
    format!("{} {} {}", lhs, op, rhs)
}

fn render_expr(e: &Expr) -> String {
    match e {
        Expr::Int(n) => n.to_string(),
        Expr::Var(v) => v.clone(),
        Expr::Field { base, field } => format!("{}.{}", base, field),
        Expr::Old(inner) => render_expr(inner),
        Expr::Unary { op, expr } => match op {
            UnOp::Neg => format!("-{}", render_expr(expr)),
        },
        Expr::Bin { op, lhs, rhs } => {
            let s = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Eq => "==",
                BinOp::Ne => "!=",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Gt => ">",
                BinOp::Ge => ">=",
                BinOp::And => "&&",
                BinOp::Or => "||",
            };
            format!("{} {} {}", render_expr(lhs), s, render_expr(rhs))
        }
    }
}

/// Like [`render_expr`] but preserves `old(...)` so contracts read faithfully in
/// doc-comments.
fn render_expr_doc(e: &Expr) -> String {
    match e {
        Expr::Int(n) => n.to_string(),
        Expr::Var(v) => v.clone(),
        Expr::Field { base, field } => format!("{}.{}", base, field),
        Expr::Old(inner) => format!("old({})", render_expr_doc(inner)),
        Expr::Unary { op, expr } => match op {
            UnOp::Neg => format!("-{}", render_expr_doc(expr)),
        },
        Expr::Bin { op, lhs, rhs } => {
            let s = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Eq => "==",
                BinOp::Ne => "!=",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Gt => ">",
                BinOp::Ge => ">=",
                BinOp::And => "&&",
                BinOp::Or => "||",
            };
            format!("{} {} {}", render_expr_doc(lhs), s, render_expr_doc(rhs))
        }
    }
}

/// Render an expression inside an `impl` method body, prefixing field/var
/// references with `self.` (invariants are written against the struct's own
/// fields).
fn render_inv(e: &Expr) -> String {
    match e {
        Expr::Int(n) => n.to_string(),
        Expr::Var(v) => format!("self.{}", v),
        Expr::Field { field, .. } => format!("self.{}", field),
        Expr::Old(inner) => render_inv(inner),
        Expr::Unary { op, expr } => match op {
            UnOp::Neg => format!("-{}", render_inv(expr)),
        },
        Expr::Bin { op, lhs, rhs } => {
            let s = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Eq => "==",
                BinOp::Ne => "!=",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Gt => ">",
                BinOp::Ge => ">=",
                BinOp::And => "&&",
                BinOp::Or => "||",
            };
            format!("{} {} {}", render_inv(lhs), s, render_inv(rhs))
        }
    }
}
